<?php
/**
 * SmartBill - View GST Invoice Details
 */

require_once __DIR__ . '/../includes/auth_check.php';

$id = (int)($_GET['id'] ?? 0);
$stmt = $pdo->prepare("
    SELECT i.*, c.mobile as customer_mobile, c.email as customer_email, c.business_name
    FROM invoices i
    LEFT JOIN customers c ON i.customer_id = c.id
    WHERE i.id = ?
");
$stmt->execute([$id]);
$invoice = $stmt->fetch();

if (!$invoice) {
    setFlash('danger', 'Invoice not found.');
    header("Location: index.php");
    exit;
}

$page_title = 'Invoice #' . $invoice['invoice_number'] . ' - SmartBill';
$company = getCompanySettings($pdo);

// Fetch items
$item_stmt = $pdo->prepare("SELECT * FROM invoice_items WHERE invoice_id = ? ORDER BY id ASC");
$item_stmt->execute([$id]);
$items = $item_stmt->fetchAll();

// Fetch payments for this invoice
$pmt_stmt = $pdo->prepare("SELECT * FROM payments WHERE invoice_id = ? ORDER BY id DESC");
$pmt_stmt->execute([$id]);
$payments = $pmt_stmt->fetchAll();

// Construct WhatsApp link
$wa_phone = preg_replace('/[^0-9]/', '', $invoice['customer_mobile'] ?? '');
if (strlen($wa_phone) === 10) $wa_phone = '91' . $wa_phone;
$wa_msg = urlencode("Dear " . $invoice['customer_name'] . ", invoice " . $invoice['invoice_number'] . " for amount " . formatCurrency($invoice['grand_total']) . " has been generated by " . ($company['company_name'] ?? 'SmartBill') . ". Outstanding balance: " . formatCurrency($invoice['outstanding_amount']) . ". Thank you.");
$wa_url = "https://api.whatsapp.com/send?phone={$wa_phone}&text={$wa_msg}";

include __DIR__ . '/../includes/header.php';
?>

<!-- Action Toolbar -->
<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center mb-4 gap-2 no-print">
    <div>
        <div class="d-flex align-items-center gap-2">
            <h4 class="fw-bold mb-0 text-dark"><?= htmlspecialchars($invoice['invoice_number']) ?></h4>
            <?php 
                $badge_class = 'badge-status-unpaid';
                if ($invoice['status'] === 'Paid') $badge_class = 'badge-status-paid';
                elseif ($invoice['status'] === 'Partially Paid') $badge_class = 'badge-status-partially';
            ?>
            <span class="<?= $badge_class ?>"><?= $invoice['status'] ?></span>
        </div>
        <p class="text-muted small mb-0">Generated on <?= formatDate($invoice['invoice_date'], 'd F Y') ?></p>
    </div>

    <div class="d-flex gap-2">
        <a href="<?= $wa_url ?>" target="_blank" class="btn btn-success btn-sm">
            <i class="fa-brands fa-whatsapp me-1"></i> Send WhatsApp
        </a>
        <a href="print.php?id=<?= $id ?>" target="_blank" class="btn btn-outline-dark btn-sm">
            <i class="fa-solid fa-print me-1"></i> Print / PDF
        </a>
        <?php if ((float)$invoice['outstanding_amount'] > 0): ?>
            <a href="../payments/create.php?invoice_id=<?= $id ?>" class="btn btn-primary btn-sm">
                <i class="fa-solid fa-hand-holding-dollar me-1"></i> Record Payment
            </a>
        <?php endif; ?>
        <a href="edit.php?id=<?= $id ?>" class="btn btn-outline-secondary btn-sm">
            <i class="fa-solid fa-pen me-1"></i> Edit
        </a>
        <a href="index.php" class="btn btn-light btn-sm border">Back</a>
    </div>
</div>

<div class="row g-4">
    <!-- Invoice Preview Card -->
    <div class="col-lg-8">
        <div class="card border-0 shadow-sm p-4">
            <!-- Header section -->
            <div class="d-flex justify-content-between pb-4 border-bottom">
                <div>
                    <?php if (!empty($company['logo'])): ?>
                        <img src="<?= $to_root . htmlspecialchars($company['logo']) ?>" alt="Logo" class="mb-2" style="max-height: 48px;">
                    <?php endif; ?>
                    <h5 class="fw-bold text-dark mb-0"><?= htmlspecialchars($company['company_name'] ?? 'SmartBill') ?></h5>
                    <div class="small text-muted"><?= htmlspecialchars($company['address'] ?? '') ?></div>
                    <div class="small text-muted"><?= htmlspecialchars($company['city'] ?? '') ?>, <?= htmlspecialchars($company['state'] ?? '') ?> - <?= htmlspecialchars($company['pin_code'] ?? '') ?></div>
                    <div class="small text-muted"><strong>GSTIN:</strong> <?= htmlspecialchars($company['gstin'] ?? '') ?></div>
                </div>
                <div class="text-end">
                    <div class="badge bg-primary-subtle text-primary border border-primary px-3 py-2 text-uppercase fw-bold fs-6 mb-2">
                        TAX INVOICE
                    </div>
                    <div class="small text-muted"><strong>Invoice No:</strong> <?= htmlspecialchars($invoice['invoice_number']) ?></div>
                    <div class="small text-muted"><strong>Date:</strong> <?= formatDate($invoice['invoice_date']) ?></div>
                    <div class="small text-muted"><strong>Due Date:</strong> <?= formatDate($invoice['due_date']) ?></div>
                    <div class="small text-muted"><strong>Place of Supply:</strong> <?= htmlspecialchars($invoice['place_of_supply']) ?></div>
                </div>
            </div>

            <!-- Buyer Details Box -->
            <div class="row py-3 border-bottom">
                <div class="col-md-6">
                    <div class="text-uppercase small fw-bold text-muted mb-1">Bill To (Customer):</div>
                    <div class="fw-bold text-dark fs-6"><?= htmlspecialchars($invoice['customer_name']) ?></div>
                    <?php if (!empty($invoice['business_name'])): ?>
                        <div class="small text-muted"><?= htmlspecialchars($invoice['business_name']) ?></div>
                    <?php endif; ?>
                    <div class="small text-muted"><?= nl2br(htmlspecialchars($invoice['customer_address'] ?? '')) ?></div>
                    <div class="small text-muted"><strong>GSTIN:</strong> <?= htmlspecialchars($invoice['customer_gstin'] ?: 'Unregistered') ?></div>
                </div>
                <div class="col-md-6 text-md-end">
                    <div class="small text-muted"><strong>Phone:</strong> <?= htmlspecialchars($invoice['customer_mobile'] ?: 'N/A') ?></div>
                    <div class="small text-muted"><strong>Email:</strong> <?= htmlspecialchars($invoice['customer_email'] ?: 'N/A') ?></div>
                    <div class="small text-muted"><strong>State:</strong> <?= htmlspecialchars($invoice['customer_state'] ?: '-') ?> (<?= htmlspecialchars($invoice['customer_state_code'] ?: '-') ?>)</div>
                    <div class="small text-muted"><strong>Reverse Charge:</strong> <?= htmlspecialchars($invoice['reverse_charge']) ?></div>
                </div>
            </div>

            <!-- Items Table -->
            <div class="table-responsive my-3">
                <table class="table table-bordered align-middle small mb-0">
                    <thead class="table-light">
                        <tr>
                            <th class="text-center" style="width: 5%;">#</th>
                            <th style="width: 32%;">Item Description</th>
                            <th class="text-center" style="width: 10%;">HSN/SAC</th>
                            <th class="text-end" style="width: 8%;">Qty</th>
                            <th class="text-end" style="width: 10%;">Rate</th>
                            <th class="text-end" style="width: 12%;">Taxable</th>
                            <th class="text-center" style="width: 8%;">GST</th>
                            <th class="text-end" style="width: 15%;">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($items as $idx => $it): ?>
                            <tr>
                                <td class="text-center"><?= $idx + 1 ?></td>
                                <td>
                                    <span class="fw-bold text-dark"><?= htmlspecialchars($it['product_name']) ?></span>
                                </td>
                                <td class="text-center font-monospace"><?= htmlspecialchars($it['hsn_sac'] ?: '-') ?></td>
                                <td class="text-end"><?= (float)$it['quantity'] ?> <?= htmlspecialchars($it['unit']) ?></td>
                                <td class="text-end"><?= formatCurrency($it['rate']) ?></td>
                                <td class="text-end"><?= formatCurrency($it['taxable_amount']) ?></td>
                                <td class="text-center"><?= (float)$it['gst_rate'] ?>%</td>
                                <td class="text-end fw-bold"><?= formatCurrency($it['total']) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <!-- Totals & In Words -->
            <div class="row pt-2">
                <div class="col-md-7">
                    <div class="p-2 bg-light rounded small mb-2">
                        <strong>Amount in Words:</strong><br>
                        <em><?= numberToWordsIndian($invoice['grand_total']) ?></em>
                    </div>
                    <?php if (!empty($invoice['notes'])): ?>
                        <div class="small text-muted mb-2">
                            <strong>Notes:</strong> <?= htmlspecialchars($invoice['notes']) ?>
                        </div>
                    <?php endif; ?>
                    <?php if (!empty($invoice['terms_conditions'])): ?>
                        <div class="small text-muted">
                            <strong>Terms:</strong> <?= nl2br(htmlspecialchars($invoice['terms_conditions'])) ?>
                        </div>
                    <?php endif; ?>
                </div>

                <div class="col-md-5">
                    <div class="border rounded p-2 small">
                        <div class="d-flex justify-content-between py-1 border-bottom">
                            <span>Subtotal:</span>
                            <span><?= formatCurrency($invoice['subtotal']) ?></span>
                        </div>
                        <?php if ((float)$invoice['discount'] > 0): ?>
                            <div class="d-flex justify-content-between py-1 border-bottom text-danger">
                                <span>Discount:</span>
                                <span>-<?= formatCurrency($invoice['discount']) ?></span>
                            </div>
                        <?php endif; ?>
                        <div class="d-flex justify-content-between py-1 border-bottom">
                            <span>Taxable Value:</span>
                            <span><?= formatCurrency($invoice['taxable_amount']) ?></span>
                        </div>
                        <?php if ((float)$invoice['cgst'] > 0): ?>
                            <div class="d-flex justify-content-between py-1 border-bottom">
                                <span>Central Tax (CGST):</span>
                                <span><?= formatCurrency($invoice['cgst']) ?></span>
                            </div>
                            <div class="d-flex justify-content-between py-1 border-bottom">
                                <span>State Tax (SGST):</span>
                                <span><?= formatCurrency($invoice['sgst']) ?></span>
                            </div>
                        <?php endif; ?>
                        <?php if ((float)$invoice['igst'] > 0): ?>
                            <div class="d-flex justify-content-between py-1 border-bottom">
                                <span>Integrated Tax (IGST):</span>
                                <span><?= formatCurrency($invoice['igst']) ?></span>
                            </div>
                        <?php endif; ?>
                        <?php if ((float)$invoice['round_off'] != 0): ?>
                            <div class="d-flex justify-content-between py-1 border-bottom text-muted">
                                <span>Round Off:</span>
                                <span><?= ((float)$invoice['round_off'] > 0 ? '+' : '') . number_format((float)$invoice['round_off'], 2) ?></span>
                            </div>
                        <?php endif; ?>
                        <div class="d-flex justify-content-between py-2 fw-bold fs-6 text-dark border-top bg-light px-2 rounded mt-1">
                            <span>Grand Total:</span>
                            <span class="text-primary"><?= formatCurrency($invoice['grand_total']) ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Right Sidebar: Payment History & Balances -->
    <div class="col-lg-4">
        <!-- Balance Card -->
        <div class="card border-0 shadow-sm mb-4">
            <div class="card-header bg-white py-3">
                <span class="fw-bold text-dark"><i class="fa-solid fa-receipt text-primary me-2"></i>Payment Status</span>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <span class="text-muted small">Total Invoice:</span>
                    <span class="fw-bold"><?= formatCurrency($invoice['grand_total']) ?></span>
                </div>
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <span class="text-muted small">Total Paid:</span>
                    <span class="fw-bold text-success"><?= formatCurrency($invoice['paid_amount']) ?></span>
                </div>
                <div class="d-flex justify-content-between align-items-center pt-2 border-top">
                    <span class="fw-bold text-dark">Balance Due:</span>
                    <span class="fs-5 fw-bold <?= ((float)$invoice['outstanding_amount'] > 0) ? 'text-danger' : 'text-success' ?>">
                        <?= formatCurrency($invoice['outstanding_amount']) ?>
                    </span>
                </div>

                <?php if ((float)$invoice['outstanding_amount'] > 0): ?>
                    <a href="../payments/create.php?invoice_id=<?= $id ?>" class="btn btn-primary w-100 mt-3">
                        <i class="fa-solid fa-plus me-1"></i> Record Payment
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <!-- Payments Ledger on this invoice -->
        <div class="card border-0 shadow-sm mb-4">
            <div class="card-header bg-white py-3">
                <span class="fw-bold text-dark"><i class="fa-solid fa-clock-rotate-left text-success me-2"></i>Payments Recorded (<?= count($payments) ?>)</span>
            </div>
            <div class="card-body p-0">
                <?php if (empty($payments)): ?>
                    <div class="p-3 text-center text-muted small">No payments recorded yet.</div>
                <?php else: ?>
                    <div class="table-responsive">
                        <table class="table table-hover align-middle mb-0 small">
                            <thead class="table-light">
                                <tr>
                                    <th>Date</th>
                                    <th>Method</th>
                                    <th class="text-end">Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($payments as $pm): ?>
                                    <tr>
                                        <td><?= formatDate($pm['payment_date'], 'd M Y') ?></td>
                                        <td>
                                            <span class="badge bg-light text-dark border"><?= htmlspecialchars($pm['payment_method']) ?></span>
                                        </td>
                                        <td class="text-end fw-bold text-success"><?= formatCurrency($pm['amount']) ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <!-- Bank & UPI Information -->
        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white py-3">
                <span class="fw-bold text-dark"><i class="fa-solid fa-building-columns text-secondary me-2"></i>Bank & UPI Details</span>
            </div>
            <div class="card-body small">
                <div class="mb-1"><strong>Bank:</strong> <?= htmlspecialchars($company['bank_name'] ?: 'N/A') ?></div>
                <div class="mb-1"><strong>A/C No:</strong> <span class="font-monospace"><?= htmlspecialchars($company['account_number'] ?: 'N/A') ?></span></div>
                <div class="mb-1"><strong>IFSC:</strong> <span class="font-monospace"><?= htmlspecialchars($company['ifsc'] ?: 'N/A') ?></span></div>
                <div><strong>UPI ID:</strong> <span class="font-monospace text-primary"><?= htmlspecialchars($company['upi_id'] ?: 'N/A') ?></span></div>
            </div>
        </div>
    </div>
</div>

<?php include __DIR__ . '/../includes/footer.php'; ?>
